name = luantidyssey
title = luantidyssey
description = A free 3D sandbox RPG on Luanti. The story is Homer's Odyssey. Odysseus has four skills.
author = atongsa
release = v1.1.1
min_minetest_version = 5.6
